<div class="text">
    <h3>1.Acceptance of Terms of Use</h3>
    <p>
        A.	Please review the following terms and conditions carefully.  This Terms of Use Agreement (“Terms”) is a legally binding contract between you and Youtoo User Licensing, LLC (“Youtoo”) regarding your access to and use of the Youtoo website or any Youtoo products, software, data feeds, and services provided to you on, from, or through the Youtoo website (collectively the “Service”).  By accessing or using the Service, you agree to the terms and conditions as outlined in this legal notice.  If you do not agree to these Terms, you should immediately stop using the Services. If the user is not an individual, then “you” means your company, its officers, members, employees, agents, representatives, successors and assigns.
    </p>
    <p>
        B.	Youtoo reserves the right to change these Terms from time to time at its sole discretion by posting such revised Terms on the Service.  You are encouraged to periodically review the most recent version on the Service.  Your continued use of the Service following any such change constitutes your agreement to follow and be bound by the Terms as changed.
    </p>
    <p>
        C.	Additional terms, such as our Privacy Policy, may apply to your use of the Service. We will post these terms on the Service and they are incorporated by reference into these Terms. If there is a conflict between these Terms and any additional terms that apply to a particular Service, the additional terms will control.
    </p>
    <p>
        D.	The Youtoo Privacy Policy contains our practices concerning data that you provide or that we may collect about you through the Service and it is incorporated by reference into these Terms.  By accessing the Service, you consent to our use of data in compliance with the Privacy Policy.
    </p>
    <h3>2.Registration and Security</h3>

    <p>
        A.	Some areas of the Service require registration for use.  In those instances, Youtoo requires that you register.  You must complete the registration process by providing Youtoo with current, complete and accurate information as prompted by the registration form.  You further agree to maintain and promptly update any registration information in order to keep it true, accurate, current and complete.  Please see our Privacy Policy for further details regarding our protection of your private information.
    </p>
    <p>
        B.	Upon registration for your account, you will choose a user identification name (i.e., your email address) and a password.  You are solely responsible for maintaining the confidentiality of your user identification name and password.  Furthermore, you understand and agree that the account is yours, individually, and that you accept responsibility for all activities, charges, and damages that occur under your account. You agree to immediately notify Youtoo if you have reason to believe that someone is using your account without your permission.  Youtoo will not be responsible for any loss or damage resulting from your failure to notify us of unauthorized use.
    </p>

    <h3>3.Use of the Service</h3>
    Youtoo hereby grants you permission to access and use the Service and its Content as set forth in these Terms, provided that you agree, without limiting any other provision in these Terms, to the following User Standards:
    <p>A.	You agree you will not access the Service or its content, information, data, text, audio, video, software, code, scripts, graphics, digital images, files, music, interactive features, comments and other materials or media (collectively, “Content”) thorough any technology, interface, or other means other that that provided by Youtoo.
    </p><p>B.	You agree you will not use the Service if you are under the age of thirteen unless you provide Youtoo with express written permission from your parent or guardian authorizing you to use the Service.
    </p><p>C.	You agree you will not alter or modify any part of the Service or its Content.
    </p><p>D.	You agree you will not distribute any part of the Service or the Content without prior written authorization from Youtoo.
    </p><p>E.	You agree you will not engage in illegal activities or Publish anything to the Service that advocates or provides instruction on illegal activity;
    </p><p>F.	You agree you will not harass, stalk, threaten, defame, or abuse other persons or entities;
    </p><p>G.	You agree you will not Publish, transmit, submit, upload, post, email or otherwise make available to the Service any Content, User Content, or other material that is inappropriate, profane, vulgar, offensive, false, disparaging, defamatory, obscene, illegal, pornographic, sexually explicit, racist, invasive of another’s privacy, libelous, or that promotes violence, racial hatred, or terrorism, or that we deem, in our sole discretion, to be otherwise objectionable;
    </p><p>H.	You agree you will not display or associate the Service in connection with any logo or mark that is not a logo or mark of the Service.
    </p><p>I.	You agree you will not do anything that could falsely suggest a relationship between Youtoo and you or any third party or that could potentially deprive Youtoo of revenue from advertising, branding, promotional activities or other sources;
    </p><p>J.	You agree you will not violate the legal rights of another person or entity including, without limitation, their intellectual property, privacy, and publicity rights;
    </p><p>K.	You agree you will not Publish material that violates or circumvents the legal rights of another person or entity, or remove, alter, or falsify intellectual property or other legal notices;
    </p><p>L.	You agree you will not Publish files that contain spyware, adware, viruses, or other such material;
    </p><p>M.	You agree you will not advertise or promote goods or services without written permission from Youtoo;
    </p><p>N.	You agree you will not interfere with use of the Service or otherwise disrupt the Service or take any action that imposes an unreasonable or disproportionately large load on the Service or its infrastructure;
    </p><p>O.	You agree you will not Publish, collect, or access personally identifiable or private information about other users;
    </p><p>P.	You agree you will not Publish, post, email or otherwise transmit any unsolicited or unauthorized promotional materials, advertising, junk mail, spam, pyramid schemes, chain letters, or other forms of solicitation;
    </p><p>Q.	You agree you will not collect or compile user information or other content thorough any unauthorized or automated means such as robots, spiders, harvesting bots, scrapers;
    </p><p>R.	You agree you will not impersonate or otherwise misrepresent your affiliation with any person or entity, including, but not limited to, a Youtoo officer or representative
    </p><p>S.	You agree you will not misrepresent the origin of materials and User Content you Publish; or
    </p><p>T.	You agree you will not circumvent or disable any access controls, access any portion of the Services that you have not been authorized to access, link to password-protected areas, attempt to access or use another user’s account or information, or allow anyone else to use your account or access information.
    </p><p>U.	You agree you will not circumvent, disable or otherwise interfere with security-related features of the Service or features that prevent or restrict use or copying of or enforce limitations on any Content.  You agree that you will not disclose or share your password with any third parties or use your password for any unauthorized purpose.
    </p><p>V.	You agree that Youtoo, in its own discretion, may restrict, terminate, or deactivate your access to the Service and its Content at any time for any reason without giving you prior notice.
    </p>


    <h3>4. User Content</h3>
    <p>A.	The Service may allow you to submit, upload, display, input, post, email or transmit (collectively, “Publish”) text, audio, video, software, scripts, graphics, digital images, files, music, interactive features, comments and other materials or media (collectively, “User Content”) to or through the Service. You understand that Youtoo does not guarantee any confidentiality or privacy, except as provided in the Privacy Policy, with respect to any User Content you submit.
    </p><p>B.	When you Publish User Content utilizing the Service, that User Content becomes public content which will be searchable and available to anyone who visits websites managed by Youtoo or uses the Service.  Such User Content may also be generally available to the public at large from search engines over the internet.  You specifically acknowledge that you have no expectation to privacy or confidentiality for any User Content Published using the Service.
    </p><p>C.	You agree that you are solely responsible for any User Content that you Publish using the Service and the consequences of Publishing your User Content on the Service.  You affirm, represent, and warrant that you own or have the legal authority and the necessary licenses, rights, consents, and permissions to any User Content you Publish.  You affirm, represent and warrant that any User Content you Publish will not contain third party copyrighted material, or material that is subject to other third party proprietary rights, unless you have permission from the rightful owner of the material or you are otherwise legally entitled to Publish the User Content. Further, you affirm, represent and warrant that any User Content you Publish conforms to all applicable local, state, federal and international laws and regulations.
    </p><p>D.	You retain all ownership rights in any Published User Content and may use your User Content for purposes outside of this agreement.  However, by Publishing your User Content, you thereby grant Youtoo (and all of its affiliated companies, agents, partners, and associated entities) a worldwide, non-exclusive, royalty-free, sub-licensable and transferable license to use, reproduce, distribute, create derivative works of, display (publically and privately), transmit, sublicense, make available, sell, translate, edit, archive and otherwise use the User Content for any purpose Youtoo sees fit (the “Content License”).  The Content License is not limited to websites owned by Youtoo and may be used or displayed in other medium, including, but not limited to television, radio, other websites, advertisements, marketing campaigns, third party platforms, and through other media channels.
    </p><p>E.	You understand and agree that the Content License extends to all other Youtoo clients, customers and product and service users. This means any Youtoo user also has a worldwide, non-exclusive, royalty-free, sub-licensable and transferable license to use, reproduce, distribute, create derivative works of, display (publically and privately), transmit, sublicense, make available, sell, translate, edit, archive and otherwise use the User Content as other users see fit.
    </p><p>F.	You may revoke the Content License by deleting or removing the User Content from the Service or delivering, via certified mail, written notice to Youtoo to remove the User Content.  However, you may not revoke the Content License as it relates to any derivative works, prior uses, or already published materials (such as advertising) created using the Content License prior to its revocation, whether such derivative works were created by Youtoo, another user, or any other third party.  You further acknowledge that copies of the User Content may survive in archived form on Youtoo’s servers and digital backups.
    </p><p>G.	You specifically acknowledge that the User Content may have been copied, reproduced, or displayed by Youtoo’s affiliates, users or third parties on other websites or through other media channels outside of Youtoo’s custody and control.  The User Content may survive in such locations despite your revocation of the Content License.  You understand that Youtoo does not have the ability to control the use of the User Content by other users or third parties outside of the Service, and while Youtoo will use commercially reasonable efforts to ensure that User Content with a revoked license will not be available through the Service, Youtoo cannot stop the use of the User Content by third parties outside of Youtoo.
    </p><p>H.	Youtoo does not endorse any User Content and reserves the right to remove the User Content at anytime, for any reason, without prior notice to any party.  Youtoo expressly disclaims any liability that may derive from the User Content. Youtoo abides by the Digital Millennium Copyright Act, and all other laws protecting copyrights, trademarks, and other intellectual property, and will remove, as soon as is commercially reasonable, any infringing User Content.
    </p><p>I.	You agree that, if your Published Content infringes on the intellectual property rights of a third party, Youtoo will cooperate with that third party, any law enforcement agency, court of law, or applicable regulatory body with the investigation into that infringement.  This means your personal information, including your name, address, email, IP address, and other identifiable information, may be distributed for the sole purpose of protecting third parties’ intellectual property.
    </p>

    <h3>5. Proprietary Rights Restrictions</h3>
    <p>A.	All Content and material on the Service, including without limitation all informational text, photographs, graphics, audio, video, messages, files, documents, images or other materials (collectively, the “Materials”), whether publicly posted or privately transmitted, as well as all derivative works, are owned by Youtoo or other parties that have licensed their material to Youtoo and is protected by copyright, trademark and other intellectual property laws.  Youtoo disclaims any proprietary interest in trademarks, service marks, logos, slogans, domain names and trade names other than its own.  Trademarks, logos, images and service marks displayed on the Service are the property of either other third parties or Youtoo.  You agree not to display or use such marks without Youtoo’s prior written permission.
    </p><p>B.	The Materials on the Service may not be copied, reproduced, republished, uploaded, posted, transmitted, or distributed in any way, including by e-mail or other electronic means.  Any modification of the Materials, use of the Materials on any web Service or networked computer environment, or use of the Materials for any purpose other than personal, non-commercial use is a violation of the copyright, trademark, and other proprietary rights in the Materials and is expressly prohibited.
    </p>

    <h3>6. Youtoo Credits</h3>
    <p>A.	Youtoo may offer users the ability to earn or purchase Youtoo credits (“Credits”) which users can redeem for upgraded services, merchandise, or other products or services (collectively, the “Rewards”) on the Youtoo Service (“Credits Program”).
    </p><p>B.	The accumulation of Credits is subject to the Credits Program Rules.  Each user is responsible for reading the Credits Program Rules and other documents which are provided in order to understand the structure for earning or purchasing Credits as well as their rights, responsibilities, and status with respect to the Credits.
    </p><p>C.	Youtoo retains the right to change, limit, modify, or cancel the Credits Program at their discretion, with or without notice.  This means that the accumulation of Credits does not entitle you to any vested rights with respect to such Credits, Rewards or Credits Program benefits. In accumulating Credits, you may not rely upon the continued availability of any Reward or Reward level, and you may not be able to obtain all offered Rewards. The number of Credits required to redeem any Reward, may be substantially increased, any Reward may be withdrawn, and restrictions on any Reward may be imposed at any time. The purchase price for Credits may be changed at any time at Youtoo’s discretion.
    </p><p>D.	All Credits, whether earned or purchased, are not owned by the user.  Rather, you have a limited right to use the Credits for Rewards within the Youtoo Service.
    </p><p>E.	Credits have no monetary value and cannot be redeemed for any sum of money.  Purchases of credits are non-refundable.
    </p><p>F.	Any and all accumulated Credits will be lost if you delete your account, or you deactivate your account for a period of six months or more, or you have no Credit earning activity on your account for a period of six months or more. Youtoo reserves the right to place expiration terms on the Credits.
    </p><p>G.	You agree that you will not sell, barter, or otherwise transfer your Credits. Any Credits so exchanged are void if transferred for cash or other consideration.
    </p><p>H.	Youtoo reserves the right to audit any and all accounts at any time and without notice to the user to ensure compliance with Youtoo’s Terms and the Credits Program Rules. In the event that an audit reveals discrepancies or violations, you may be prohibited from earning, purchasing, or redeeming Credits as determined in Youtoo’s sole discretion.
    </p>


    <h3>7. Links to Other Web Services</h3>
    <p>The Service contains links to third party services and websites. The linked services and websites are not under Youtoo's control and Youtoo does not endorse, adopt or assume any responsibility for the content or privacy practices or other practices of any linked service or website. You should review third parties' terms of use and privacy policies before you use their services. By using the Service, you expressly relieve Youtoo from any and all liability arising from your use of any third party service or website.
    </p>

    <h3>8. Disclaimer of Warranties</h3>
    <p>
        A.	YOU EXPRESSLY AGREE THAT USE OF THE SERVICE IS AT YOUR SOLE RISK.  THE SERVICE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS.  YOUTOO EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NON-INFRINGEMENT.
    </p><p>B.	YOUTOO MAKES NO WARRANTY THAT THE SERVICE WILL MEET YOUR REQUIREMENTS, OR THAT THE SERVICE WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR FREE; NOR DOES YOUTOO MAKE ANY WARRANTY AS TO THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE SERVICE.
    </p><p>C.	YOU UNDERSTAND AND AGREE THAT ANY MATERIAL AND/OR DATA DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THE SERVICE IS AT YOUR OWN DISCRETION AND RISK AND THAT YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF SUCH MATERIAL AND/OR DATA.
    </p><p>D.	YOU UNDERSTAND AND AGREE THAT YOUTOO DOES NOT GUARANTEE THE ACCURACY OR COMPLETENESS OF ANY INFORMATION PROVIDED AT OR IN CONNECTION WITH THE SERVICE.  YOUTOO IS NOT RESPONSIBLE FOR ANY ERRORS OR OMISSIONS OR FOR THE RESULTS OBTAINED FROM THE USE OF SUCH INFORMATION.
    </p><p>E.	YOUTOO SHALL NOT BE RESPONSIBLE FOR ANY LOSS OR DAMAGE CAUSED, OR ALLEGED TO HAVE BEEN CAUSED, DIRECTLY OR INDIRECTLY, BY THE INFORMATION OR IDEAS CONTAINED, SUGGESTED OR REFERENCED AT THE SERVICE.  YOUR USE OF THE SERVICE IS SOLELY AT YOUR OWN RISK.  NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM YOUTOO OR THROUGH THE SERVICE SHALL CREATE ANY WARRANTY NOT EXPRESSLY MADE HEREIN.
    </p><p>F.	YOUTOO MAKES NO WARRANTY REGARDING ANY PRODUCTS OR SERVICES PURCHASED OR OBTAINED THROUGH THE SERVICE OR ANY TRANSACTIONS ENTERED INTO THROUGH THE SERVICE.
    </p>

    <h3>9. Indemnification</h3>
    <p>A.	You agree to indemnify, defend and hold harmless Youtoo, its officers, directors, employees, agents, information providers and suppliers from and against all losses, expenses, damages and costs, including reasonable attorney’s fees, resulting from any violation of this agreement or any activity arising from or related to your use of the Service, User Content (including infringement of third parties’ intellectual property rights or negligent or wrongful conduct) or any transaction you enter into with a third party based on information or contacts obtained from the Service whether by you or any other person accessing the Service using your account.
    </p>

    <h3>10. Limitation of Liability</h3>
    <p>A.	YOU AGREE THAT NEITHER YOUTOO, NOR ITS OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, INFORMATION PROVIDERS OR SUPPLIERS SHALL HAVE ANY LIABILITY TO YOU UNDER ANY THEORY OF LIABILITY OR INDEMNITY IN CONNECTION WITH YOUR USE OF OR INABILITY TO USE THE SERVICE OR RESULTING FROM UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR TRANSMISSIONS OR DATA, INCLUDING BUT NOT LIMITED TO, DAMAGES FOR LOSS OF PROFITS, USE, DATA OR OTHER INTANGIBLES EVEN IF FORESEEABLE OR YOUTOO HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.  YOU HEREBY RELEASE AND FOREVER WAIVE ANY AND ALL CLAIMS YOU MAY HAVE AGAINST YOUTOO, ITS OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, INFORMATION PROVIDERS OR SUPPLIERS FOR LOSSES OR DAMAGES YOU SUSTAIN IN CONNECTION WITH YOUR USE OF OR INABILITY TO USE THE SERVICE.
    </p><p>B.	NOTWITHSTANDING THE FOREGOING PARAGRAPH, THE TOTAL LIABILITY OF YOUTOO, ITS OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, INFORMATION PROVIDERS AND SUPPLIERS, IF ANY, FOR LOSSES OR DAMAGES SHALL NOT EXCEED THE FEES PAID BY YOU FOR THE PARTICULAR INFORMATION OR SERVICE PROVIDED.  IN NO EVENT SHALL YOUTOO, ITS OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, INFORMATION PROVIDERS OR SUPPLIERS BE LIABLE TO YOU FOR ANY LOSSES OR DAMAGES OTHER THAN THE AMOUNT REFERRED TO ABOVE.  ALL OTHER DAMAGES, DIRECT OR INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL OR PUNITIVE ARISING FROM ANY USE OF OR INABILITY TO USE THE INFORMATION OR OTHER PARTS OF YOUTOO ARE HEREBY EXCLUDED EVEN IF YOUTOO, ITS OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, INFORMATION PROVIDERS OR SUPPLIERS HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
    </p>

    <h3>11. Failure to Abide by these Terms</h3>
    <p>Youtoo may in its sole discretion terminate or suspend your account and any current activities at the Service immediately without notice to you if you breach these Terms or if we are unable to verify or authenticate any information that you provide to us. Youtoo reserves the right, in its sole discretion, to refuse access to any user at any time to those portions of the Service that require registration. You agree that Youtoo shall not be liable to you or any third party for any termination of your access to any Material and/or the Service.
    </p>
    <h3>12. Governing Law; Consent to Jurisdiction</h3>
    <p>You agree that these Terms are governed by the laws of the State of Texas and that proper and convenient venue lies exclusively with the courts of Dallas County, Texas. You agree to be subject to the personal jurisdiction of the State and federal courts sitting in or having jurisdiction over Dallas County, Texas, U.S.A. in the event that any litigation results concerning any aspect arising out of these Terms of Use.
    </p>
    <h3>13. Miscellaneous</h3>
    <p>These Terms constitute the entire agreement between you and Youtoo with respect to the Service. If any provision of these Terms is found to be invalid or unenforceable by a court of competent jurisdiction, such provision shall be severed from the remainder of the Terms, which shall remain in full force and effect. No waiver by either party of any breach or default hereunder shall be deemed to be a waiver of any preceding or subsequent breach or default. The section headings used herein are for convenience only.
        YOU ACKNOWLEDGE THAT YOU HAVE READ THESE TERMS, UNDERSTAND THEM, AND AGREE TO BE BOUND BY THEIR TERMS AND CONDITIONS. YOU FURTHER AGREE THAT IT IS THE COMPLETE AND EXCLUSIVE STATEMENT OF THE AGREEMENT BETWEEN YOU AND YOUTOO WHICH SUPERSEDES ANY PROPOSED OR PRIOR AGREEMENT, ORAL OR WRITTEN, AND ANY OTHER COMMUNICATIONS BETWEEN YOU AND YOUTOO RELATING TO YOUR USE OF THE SERVICE.
        If you have any questions or comments about these Terms, you can contact Youtoo at info@youtoo.com.
    </p>
</div>