<p>
    <b>Términos de Presentación</b>
    <br/>
    <br/>
NBCUniversal Media, LLC, con domicilio social en 30 Rockefeller Plaza, New York, New York 10112 (“NBCU”) le invita a divertirse con Telemundo ofreciéndole la oportunidad de presentar videos o fotos de su persona en conexión con varias promociones (“Contenido del usuario”). Debe ser mayor de dieciocho años de edad para poder participar. 
<br/>
<br/>
Al presentar su Contenido del usuario, usted acuerda que el mismo podrá ser transmitido por televisión, subido al Sitio web de NBCU localizado en http://www.telemundo.com (“Sitio web”) y usado en publicidad de NBCU en sus transmisiones y fuera del aire, y en el Sitio web (conjuntamente, “Materiales de contenido del usuario”) y acuerda también que NBCU podrá explotar su Contenido del usuario y los Materiales de contenido del usuario a su exclusiva discreción y en cualquier y todo medio y plataforma de distribución ahora conocidos o por ser conocidos en el futuro, a través del mundo y en perpetuidad. 
<br/>
<br/>
Al presentar su Contenido del usuario, usted reconoce y acuerda aquí que está otorgando a NBCU (incluyendo, de manera abreviada pero no exhaustiva, a sus licenciatarios, sucesores y cesionarios) un derecho y una licencia a nivel mundial, libre de regalías, perpetua, irrevocable y sublicenciable para usar, reproducir, exhibir o interpretar públicamente, modificar, sublicenciar y distribuir tal contenido e incorporarlo en otras obras, en su totalidad o en parte, de cualquier manera y en todo medio y plataforma de distribución ahora conocidos o por ser conocidos en el futuro. Usted además declara y garantiza ser el propietario de tales contenidos o, de otro modo, que goza de los suficientes derechos sobre los contenidos para otorgar a NBCU la licencia mencionada aquí sin infringir ni violar derechos de terceros. Sin perjuicio de lo anteriormente mencionado, usted reconoce y acuerda que NBCU y sus licenciatarios, sucesores y cesionarios gozarán de todos los derechos para poder vender, licenciar, ceder y de todo otro modo transferir cualquier y todo derecho otorgado por Usted a NBCU bajo estos Términos de Presentación y a exhibir cualquier anuncio publicitario, publicidad, material promocional y derecho de distribución en conexión con su Contenido del usuario. Usted reconoce y acuerda además que NBCU, sus licenciatarios, sucesores y cesionarios, tendrán derecho a retener cualquier y toda ganancia generada por cualquier venta, licencia, cesión y transferencia de los derechos otorgados por Usted aquí, como así también cualquier y toda ganancia generada por la exhibición de cualquier anuncio publicitario, publicidad, material promocional y derecho de distribución en conexión con su Contenido del usuario. Nada de lo contenido en estos Términos de Presentación obliga, o será interpretado como que obliga a NBCU o a cualquier otra persona o entidad, a ejercer cualquiera de los derechos otorgados por Usted bajo estos Términos de Presentación. Usted reconoce además que no recibirá ningún tipo de compensación por su Contenido del usuario, o por el uso que se haga del mismo, y acuerda aquí que no existe ninguna industria, costumbre o práctica que varíe estos Términos de Presentación. Usted acuerda también que NBCU, sus licenciatarios, sucesores y/o cesionarios, no tendrán ninguna obligación de darle crédito (es decir, reconocimiento) por su Contenido del usuario pero, a su absoluta discreción, pudieran decidir hacerlo.
<br/>
<br/>
Al presentar su Contenido del usuario, usted está implícita y voluntariamente dando su consentimiento para la grabación y  uso inicial  y repetido por parte de NBCU, sus licenciatarios, sucesores y cesionarios, de su voz, acciones, semejanza, nombre, apariencia, fotografía de perfil, interpretación, material biográfico y cualquier otra información que lo identifique, incluyendo, de manera abreviada pero no exhaustiva, cualquier información contenida en su Contenido del usuario, de cualquier modo que sea usada, editada, alterada, novelizada o modificada por NBCU, a su absoluta discreción, en cualquier y todo medio o plataforma de distribución ahora conocidos o por ser inventados, a través del mundo y en perpetuidad, incluyendo, de manera abreviada pero no exhaustiva, en y en conexión con NBCU o sitios o servicios relacionados, en y en conexión con cualquier programa de televisión y otras producciones, y en y en conexión con cualquier iniciativa de difusión, promoción y/o publicidad.  
<br/>
<br/>
No se acusará recibo de su Contenido del usuario y dicho Contenido del usuario no será devuelto y Usted reconoce y acuerda que está enviando dicho Contenido del usuario de manera voluntaria y sin exigencias ni expectativas de confidencialidad y que no se está creando, ni se tiene la intención de crear, ningún tipo de relación confidencial entre NBCU y/o cualquier otra persona o entidad por un lado, ni por su presentación del Contenido del usuario por el otro. Usted entiende además que si su Contenido del usuario es seleccionado para ser usado, tal uso no será considerado una oportunidad de empleo. Si Usted no desea que su Contenido del usuario sea usado y transmitido por NBCU, no participe. 
<br/>
<br/>
NBCU no tendrá ningún tipo de obligación de copiar, publicar, exhibir o de todo otro modo explotar los Materiales de contenido del usuario o su Contenido del usuario. Su Contenido del usuario pudiera no ser identificable.  NBCU tendrá derecho a realizar cualesquiera cambios que considere convenientes, a su exclusiva discreción, sobre su Contenido del usuario. Su Contenido del usuario no deberá contener ningún tipo de material violento, pornográfico, obsceno, ilegal, inapropiado, racista o moralmente ofensivo. Usted debe contar con la autorización de cualquier persona que usted identifique o a la cual se refiera en su Contenido del usuario. Su Contenido del usuario deberá ser de su propia y única autoría. Su Contenido del usuario deberá también cumplir con los Términos de Servicio de YouToo y las especificaciones de usuarios de video y/o fotos subidas.
<br/>
<br/>
Usted entiende que al usar el Sitio web pudiera encontrarse con contenidos que pudieran ser considerados ofensivos, indecentes o censurables y que, dentro de dichos contenidos, se pudiera encontrar algún lenguaje o vocabulario de índole explícitamente sexual. Sin embargo, usted acuerda usar el Sitio web por su propia cuenta y riesgo y acuerda también que NBCU no tendrá ningún tipo de responsabilidad por los contenidos que pudieran ser considerados ofensivos, indecentes o censurables. Los contenidos publicados en el Sitio web son provistos por usuarios como usted quienes no están de ningún modo afiliados a NBCU, y cada uno de dichos usuarios, es el único responsable por el contenido que haya publicado. Esto significa que usted, y no NBCU, es el único responsable por y susceptible a las consecuencias de cualquier reclamo, pérdida o daño y perjuicio relacionado con su Contenido del usuario y por todo otro contenido que usted suba, publique, envíe por correo electrónico o, de todo otro modo, transmita a través del Sitio web. 
NBCU no es responsable por los contenidos que los usuarios suben ni por la exactitud u opiniones expresadas en el Sitio web. NBCU no investiga, no monitorea y no revisa los Contenidos del usuario para garantizar su exactitud o integridad. 
<br/>
<br/>
En la medida en que los Términos y condiciones de uso del Sitio web localizado en http://msnlatino.telemundo.com/legal_terms/ (los “Términos del Sitio web”) no estén en conflicto con estos Términos de Presentación, los Términos del Sitio web aplican. 
<br/>
<br/>
</p>
<br/>
<p>
    <b>Telemundo terms of submission</b>
    <br/>
    <br/>
NBCUniversal Media, LLC, located at 30 Rockefeller Plaza, New York, New York 10112 (“NBCU”) invites you to join in on the fun with Telemundo by giving you the opportunity to submit videos and photos of yourself in connection with various promotions (the “User Content”). In order to participate, you must be at least 18 years old.
<br/>
<br/>
By submitting your User Content, you agree that your User Content may be broadcast on-air, on NBCU’s website located at http://www.telemundo.com (the “Website”), and in advertising for NBCU on-air and off-air and on the Website, (together, “User Content Materials”), and that NBCU may exploit your User Content and the User Content Materials howsoever it chooses in any and all media now or hereafter known, throughout the world in perpetuity. 
<br/>
<br/>
By submitting your User Content, you hereby acknowledge and agree that you are granting NBCU (including without limitation, its licensees, successors, and assigns) a worldwide, royalty-free, perpetual, irrevocable, sub-licensable, non-exclusive right and license to use, reproduce, publicly display, publicly perform, modify, sublicense, and distribute such content, and incorporate it in other works, in whole or in part, in any manner and any media now known or hereafter developed. You represent and warrant that you own such content or otherwise have sufficient rights in the content to grant to NBCU the foregoing license without infringing or violating the rights of any third party. Without in any way limiting the foregoing, you acknowledge and agree that NBCU, its licensees, successors and assigns, shall have the right to sell, license, assign and otherwise transfer any and all of the rights granted by you to NBCU under these Terms of Submission, and to display any advertising, publicity, promotional materials and distribution rights in connection with your User Content. You acknowledge and agree that NBCU, its licensees, successors and assigns, will be entitled to retain any and all revenue generated from any sales, licenses, assignments and other transfers of the rights granted by you hereunder, as well as any and all revenue generated by the display of any advertising, publicity, promotional materials or distribution rights in connection with your User Content. Nothing in these Terms of Submission obligates or may be deemed to obligate NBCU or any other person or entity to exercise any of the rights granted by you under these Terms of Submission. You will not receive any compensation of any kind for your User Content or the use thereof, and you agree that there is no industry or other custom or practice that will vary these Terms of Submission.  You agree that NBCU, its licensees, successors and/or assigns, shall have no obligation to give you credit for your User Content, but in their sole discretion may elect to do so.
<br/>
<br/>
By submitting your User Content, you consent to the recording, use and reuse by NBCU, its licensees, successors and assigns, of your voice, actions, likeness, name, appearance, profile photograph, performance, biographical material, and any other identifying information, including, without limitation, any information contained in your User Content, as used, edited, altered, fictionalized or modified by NBCU, in its sole discretion, in any and all media now known or hereafter devised, throughout the world, in perpetuity, including, without limitation, in and in connection with NBCU, or related sites or services, in and in connection with any television programs and other productions, and in and in connection with advertising, promotion and publicity.
<br/>
<br/>
Your User Content will not be acknowledged or returned. You acknowledge and agree that you are sending your User Content voluntarily, and not in confidence, and that no confidential relationship is intended or created between NBCU, and/or any other person or entity, on the one hand, and you, on the other hand, by your submission of your User Content.  You understand that if your User Content is selected for use, such use will not be considered an employment opportunity. If you do not want your User Content to be used and broadcast by NBCU, then please do not participate.
<br/>
<br/>
NBCU shall have no obligation to copy, publish, display, or otherwise exploit the User Content Materials or your User Content.  Your User Content may not be identifiable.  NBCU will have the right to make any changes to your User Content as it determine in its sole discretion. Your User Content should not contain material that is violent, pornographic, obscene, illegal, inappropriate, or racially or morally offensive. You must have the permission of any person that you identify or otherwise refer to in your User Content. Your User Content must be your own original work. Your User Content must also comply with YouToo terms of service and specifications for user video and/or photo uploads.
<br/>
<br/>
You understand that by using the Website, you may encounter content that may be deemed offensive, indecent, or objectionable, which content may or may not be identified as having explicit language. Nevertheless, you agree to use the Website at your sole risk and that the NBCU shall not have any liability to you for content that may be found to be offensive, indecent, or objectionable. Content posted through the Website is provided by users like you who are unaffiliated with NBCU, and the user providing content is solely responsible for its content. This means that you, and not NBCU, are entirely responsible and liable for any claims, loss or damages relating to your User Content and all other content that you upload, post, email or otherwise transmit via the Website. NBCU is not responsible for any User Content, accuracy or opinions expressed on the Website, and NBCU does not investigate, monitor or check for accuracy or completeness of any User Content. 
<br/>
<br/>
To the extent that the Website’s Terms and Conditions of Use, located at http://msnlatino.telemundo.com/legal_terms/ (the “Website Terms”), are not in conflict with these Terms of Submission, the Website Terms apply.
<br/>
<br/>
</p>