<?php

return array(
    'Title cannot be blank' => 'El título no puede estar en blanco',
    'Image cannot be blank' => 'La imagen no puede estar en blanco',
    'Day' => 'Día',
    'Month' => 'Mes',
    'Year' => 'Año',
    'January' => 'Enero',
    'February' => 'Febrero',
    'March' => 'Marzo',
    'April' => 'Abril',
    'May' => 'Mayo',
    'June' => 'Junio',
    'July' => 'Julio',
    'August' => 'Agosto',
    'September' => 'Septiembre',
    'October' => 'Octubre',
    'November' => 'Noviembre',
    'December' => 'Diciembre',
    'You must be 18 or older' => 'Usted debe ser mayor de 18 años',
    'Video cannot be blank' => 'La video no puede estar en blanco',
    'No Polls Open' => 'SIN VOTACIÓN ABRE!',
    'Gender cannot be blank' => 'El género no puede estar en blanco',
    'First Name cannot be blank' => 'Nombre no puede estar en blanco',
    'Last Name cannot be blank' => 'Apellido no puede estar en blanco',
    'Password cannot be blank' => 'La contraseña no puede estar en blanco',
    'The Birthday Month, Day, Year must be selected' => 'El mes de cumpleaños, día, año debe seleccionarse',
    'You must be 18 or older' => 'Usted debe ser mayor de 18 años',
    'Username cannot be blank' => 'Nombre de usuario no puede estar en blanco',
    'New Password cannot be blank' => 'Nueva contraseña no puede estar en blanco',
    'New Password Confirm cannot be blank' => 'Nueva contraseña Confirmar no puede estar en blanco',
    'New passwords do not match' => 'Las nuevas contraseñas no coinciden',
    'New Password is too short (minimum is 6 characters)' => 'Nueva contraseña es demasiado corto (mínimo es de 6 caracteres)',
    'Sorry, this username has already been used' => 'Lo sentimos, este nombre de usuario ya ha sido utilizado',
    'Email cannot be blank' => 'El correo electrónico no puede estar en blanco',
    'Email is not a valid email address' => 'Email no es una dirección válida de correo electrónico',
    'Email {value} has already been taken' => 'Email {value} ya se ha tomado',
    'Send' => 'enviar',
    'Department' => 'Departamento',
    'What can we help you with today?' => '¿Qué podemos ayudarle hoy?',
);
?>